# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
env:
  browser: false
  node: true
  es6: true
  mocha: true
extends:
  - eslint:recommended
parserOptions:
  ecmaVersion: 2019
rules: {
  require-await: 2
}
