# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
#
# This sets up the AWS infrastructure to copy RDS DB Snapshots off to a separate DR account
# This template is for the consumer of the snapshots
# Remember that to give the producer account publish access to the DR topic you need both an identity policy on the source side and a resource policy on this side!
# Show ABAC for the DR account to delete the snapshot copies in the Source account.
#
AWSTemplateFormatVersion: "2010-09-09"
Description: "A CloudFormation Template for Copying DB Snapshots to another (DR) account"

Parameters:
  CodeBucket:
    Description: The S3 bucket containing the code
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    Default: draco
    Type: String
  CodePrefix:
    Description: The S3 prefix within the bucket (may or may not have a trailing slash!)
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    Default: draco/
    Type: String
  DeploymentTimestamp:
    Description: The time of deploy used to trigger the fetch of the latest code
    Default: 2000-01-01T00:00:00
    Type: String
  SourceAcct:
    Description: The account that shares the snapshot copies to be DRd
    Default: 111111111111
    Type: String
  TargetAcct:
    Default: 222222222222
    Description: The account that saves the DR Snapshots
    Type: String
  DrTagKey:
    Description: The tag key that identifies snapshot transit copies made for DR
    Default: DR
    Type: String
  DrTagValue:
    Description: The tag value that identifies snapshot transit copies made for DR
    Default: DRSnapshotCopy
    Type: String

Resources:

  DracoRegionalBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "draco-${AWS::AccountId}-${AWS::Region}"
      VersioningConfiguration:
        Status: Enabled

  CopyObjects:
    Type: Custom::CopyObjects
    Properties:
      DeploymentTimestamp: !Ref DeploymentTimestamp
      ServiceToken: !GetAtt CopyObjectsFunction.Arn
      DestBucket: !Ref DracoRegionalBucket
      SourceBucket: !Ref CodeBucket
      PhysicalResourceId: DracoFiles
      Prefix: !Ref CodePrefix
      Objects:
        - producer.zip
        - producer.yaml
        - wait4copy.zip
        - wait4copy.yaml
    
  CopyObjectsRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Path: /
      Policies:
        - PolicyName: lambda-copier
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource:
                  - !Sub 'arn:aws:s3:::${CodeBucket}/${CodePrefix}*'
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:DeleteObject
                Resource:
                  - !Sub 'arn:aws:s3:::${DracoRegionalBucket}/${CodePrefix}*'
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub 'arn:aws:s3:::${DracoRegionalBucket}'

  # Copies objects from a source S3 bucket to a destination if they don't already exist.
  # It returns the S3 object versions. The main use for this is as the S3ObjectVersion
  # parameter in Lambda functions defined elsewhere in the template, allowing the code to
  # be updated, or not depending whether a new version has been uploaded.
  CopyObjectsFunction:
    Type: AWS::Lambda::Function
    Properties:
      Description: Copies objects from a source S3 bucket to a destination
      Handler: index.handler
      Runtime: python3.7
      Role: !GetAtt CopyObjectsRole.Arn
      Timeout: 240
      Code:
        ZipFile: |
            import boto3
            import botocore
            import cfnresponse
            import logging
            import threading
            from datetime import datetime

            logging.getLogger().setLevel(logging.INFO)

            def copy_objects(source_bucket, dest_bucket, prefix, objects):
                s3 = boto3.client('s3')
                versions = {}
                etags = {}
                for o in objects:
                    try:
                        rsp = s3.head_object(Bucket=dest_bucket, Key=prefix+o)
                        versions[o] = rsp['VersionId']
                        etags[o] = rsp['ETag']
                    except botocore.exceptions.ClientError as error:
                        if source_bucket == dest_bucket:
                            raise error
                        versions[o] = None
                        etags[o] = '-'

                    logging.debug(f'{dest_bucket}/{prefix+o}: version={versions[o]}, etag={etags[o]}')

                    if source_bucket != dest_bucket:
                        try:
                            crsp = s3.copy_object(CopySource=f'{source_bucket}/{prefix+o}',
                                                  Bucket=dest_bucket, Key=prefix+o,
                                                  CopySourceIfNoneMatch=etags[o])
                            versions[o] = crsp['VersionId']
                            logging.debug(f'{dest_bucket}/{prefix+o}: copied version={versions[o]}')
                        except botocore.exceptions.ClientError as error:
                            logging.debug(f'{dest_bucket}/{prefix+o}: up-to-date')
                            if error.response['Error']['Code'] != 'PreconditionFailed':
                                raise error

                return versions


            def timeout(event, context):
                logging.error('Execution is about to time out, sending failure response to CloudFormation')
                cfnresponse.send(event, context, cfnresponse.FAILED, {}, None)


            def handler(event, context):
                # make sure we send a failure to CloudFormation if the function
                # is going to timeout
                timer = threading.Timer((context.get_remaining_time_in_millis()
                                         / 1000.00) - 0.5, timeout, args=[event, context])
                timer.start()
                status = cfnresponse.SUCCESS
                responseData = {}
                try:
                    source_bucket = event['ResourceProperties']['SourceBucket']
                    dest_bucket = event['ResourceProperties']['DestBucket']
                    physical_resource_id = event['ResourceProperties']['PhysicalResourceId']
                    prefix = event['ResourceProperties']['Prefix']
                    objects = event['ResourceProperties']['Objects']
                    if event['RequestType'] != 'Delete': # Leave the objects in the bucket
                        versions = copy_objects(source_bucket, dest_bucket, prefix, objects)
                        responseData = versions
                        logging.info(f'Versions: {versions}')
                except Exception as e:
                    logging.error(f'Exception: {e}', exc_info=True)
                    status = cfnresponse.FAILED
                finally:
                    timer.cancel()
                    cfnresponse.send(event, context, status, responseData, physical_resource_id)
    
  SnapshotEncryptionKey:
    Type: AWS::KMS::Key
    Properties:
      Description: Key used for encrypting transit copies
      Enabled: true
      EnableKeyRotation: false
      KeyPolicy:
        Version: '2012-10-17'
        Id: transit_key_policy
        Statement:
        - Sid: Allow Source Account Full Access
          Effect: Allow
          Principal:
            AWS:
              - !Sub ${AWS::AccountId}
          Action: kms:*
          Resource: '*'
        - Sid: Lambda function to copy encrypted RDS Snapshots
          Effect: Allow
          Principal:
            AWS: 
              - !GetAtt LambdaExecutionRole.Arn
          Action:
            - kms:Encrypt
            - kms:Decrypt
            - kms:ReEncrypt*
            - kms:GenerateDataKey*
            - kms:ListGrants
            - kms:RevokeGrant
            - kms:CreateGrant
            - kms:DescribeKey
          Resource: '*'
        - Sid: DR account copy encrypted RDS Snapshots
          Effect: Allow
          Principal: "*"
          Action:
            - kms:Encrypt
            - kms:Decrypt
            - kms:ReEncrypt*
            - kms:GenerateDataKey*
            - kms:ListGrants
            - kms:RevokeGrant
            - kms:CreateGrant
            - kms:DescribeKey
          Resource: '*'
          Condition:
            StringEquals:
              aws:PrincipalAccount: !Ref TargetAcct

  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: CloudwatchLogs
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - logs:GetLogEvents
              Resource:
                - !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:*
        - PolicyName: ManipulateSnapshots
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - rds:CopyDBSnapshot
                - rds:CopyDBClusterSnapshot
                - rds:DeleteDBSnapshot
                - rds:DeleteDBClusterSnapshot
                - rds:ModifyDBSnapshotAttribute
                - rds:ModifyDBClusterSnapshotAttribute
                - rds:DescribeDBSnapshots
                - rds:DescribeDBClusterSnapshots
                - rds:ListTagsForResource
                - ec2:CopySnapshot
                - ec2:CreateTags
                - ec2:DescribeTags
                - ec2:ModifySnapshotAttribute
                - ec2:DeleteSnapshot
              Resource: '*'
        - PolicyName: AllowPublish2DrTopic
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - sns:Publish
              Resource: !Sub "arn:aws:sns:${AWS::Region}:${TargetAcct}:DracoConsumer"
        - PolicyName: AllowStepfunctions
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action:
                - states:StartExecution
              Resource: !Sub "arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:wait4copy-${AWS::AccountId}"
  

  SnapshotTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      Topics:
        - !Ref SnapshotTopic
      PolicyDocument:
        Version: '2012-10-17'
        Id: SetupSnapshotTopic
        Statement:
        - Sid: Defaults
          Effect: Allow
          Principal:
            AWS: "*"
          Action:
            - sns:GetTopicAttributes
            - sns:SetTopicAttributes
            - sns:AddPermission
            - sns:RemovePermission
            - sns:DeleteTopic
            - sns:Subscribe
            - sns:ListSubscriptionsByTopic
            - sns:Publish
            - sns:Receive
          Resource: !Ref SnapshotTopic
          Condition:
            StringEquals:
              AWS:SourceOwner: !Ref SourceAcct
        - Sid: AllowTargetPublish
          Effect: Allow
          Principal:
            AWS: !Ref TargetAcct
          Action:
            - sns:Publish
          Resource: !Ref SnapshotTopic


  SnapshotTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: Topic for Snapshot Processing
      TopicName: DracoProducer
      Subscription:
      - Endpoint: !GetAtt SnapshotHandlerLambda.Arn
        Protocol: lambda


  SnapshotEventSubscription:
    Type: AWS::RDS::EventSubscription
    Properties:
      Enabled: true
      SourceType: db-snapshot
      SnsTopicArn: !Ref SnapshotTopic
      EventCategories:
      - creation

  ClusterSnapshotEventSubscription:
    Type: AWS::RDS::EventSubscription
    Properties:
      Enabled: true
      SourceType: db-cluster-snapshot
      SnsTopicArn: !Ref SnapshotTopic
      EventCategories:
      - backup

  EventBridgeSubscriptions:
    Type: AWS::Events::Rule
    Properties:
      EventPattern:
        source:
          - aws.ec2
        detail-type:
          - EBS Snapshot Notification
        detail:
          event:
            - createSnapshot
      State: ENABLED
      Targets:
        - Arn: !GetAtt SnapshotHandlerLambda.Arn
          Id: DracoHandler

  EventInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn: !GetAtt EventBridgeSubscriptions.Arn
      FunctionName: !GetAtt SnapshotHandlerLambda.Arn

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      Principal: sns.amazonaws.com
      SourceArn: !Ref SnapshotTopic
      FunctionName: !GetAtt SnapshotHandlerLambda.Arn

  SnapshotHandlerLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Code that copies the snapshot and shares it with the target
      Environment:
        Variables:
          DR_ACCT: !Ref TargetAcct
          DR_TOPIC_ARN: !Sub "arn:aws:sns:${AWS::Region}:${TargetAcct}:DracoConsumer"
          KEY_ARN: !GetAtt SnapshotEncryptionKey.Arn
          SM_COPY_ARN: !Sub "arn:aws:states:${AWS::Region}:${AWS::AccountId}:stateMachine:wait4copy-${AWS::AccountId}"
          TAG_KEY: !Ref DrTagKey
          TAG_VALUE: !Ref DrTagValue
      Handler: producer.handler
      Runtime: nodejs12.x
      Timeout: 60
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        S3Bucket: !Ref DracoRegionalBucket
        S3Key: !Sub "${CodePrefix}producer.zip"
        S3ObjectVersion: !GetAtt CopyObjects.producer.zip

  DracoLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${SnapshotHandlerLambda}"
      RetentionInDays: 90

  CloudWatchErrorMetric:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: "ERROR"
      LogGroupName: !Ref DracoLogGroup
      MetricTransformations:
        - MetricValue: "1"
          DefaultValue: 0
          MetricNamespace: "Draco/SnapshotHandler"
          MetricName: "ErrorCount"

  CloudWatchWarnMetric:
    Type: AWS::Logs::MetricFilter
    Properties:
      FilterPattern: "WARN"
      LogGroupName: !Ref DracoLogGroup
      MetricTransformations:
        - MetricValue: "1"
          DefaultValue: 0
          MetricNamespace: "Draco/SnapshotHandler"
          MetricName: "WarnCount"

  Wait4Copy:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${DracoRegionalBucket.RegionalDomainName}/${CodePrefix}wait4copy.yaml"
      Parameters:
        CodeBucket: !Ref DracoRegionalBucket
        CodeKey: !Sub "${CodePrefix}wait4copy.zip"
        CodeVersion: !GetAtt CopyObjects.wait4copy.zip
        NotifyTopicArn: !Ref SnapshotTopic

Outputs:

  DracoRegionalBucket:
    Value: !Ref DracoRegionalBucket

  ProducerTopicArn:
    Value: !Ref SnapshotTopic

# vim: sts=2 et sw=2:
